# Generated by Django 3.2.6 on 2021-08-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('timeup', 'Time Up')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text="\n    The choices field is only used if the question type is 'radio' and 'select'. \n    Provide a comma-separated list of options for this question\n    ", null=True),
        ),
    ]
